flowchart TD
    A[1. Gestores] --> A1[jsa-gestores-basic-inf.sql]
    A --> A2[jsa-gestores-caterogys.sql]
    B[2. Profesores] --> B1[jsa-profesors-basic-inf.sql]
    B --> B2[jsa-profesors-manage-course.sql]
    C[3. Estudiantes] --> C1[jsa-students-basic-inf.sql]
    C --> C2[jsa-students-inscriptions.sql]
    C --> C3[jsa-students-califications.sql]
    D[4. Actividades] --> D1[jsa-actividades-curso.sql]
    D --> D2[jsa-course-activities-details.sql]